apiVersion: v1
kind: Service
metadata:
  labels:
    app: lilypad-bot
  name: lilypad-bot
  namespace: default
spec:
  ports:
    - name: lilypad-bot
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: lilypad-bot
